python-install-mirror = "https://github.hlug.cn/https://github.com/astral-sh/python-build-standalone/releases/download/"

[[index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true
