name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dotfiles:$(date +%s)

  windows-info:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print Windows system information
      run: |
        echo "=== Windows System Information ==="
        echo "Windows Version:"
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        echo ""
        echo "Visual Studio Version:"
        if (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe") {
          echo "Visual Studio 2022 Enterprise is installed"
        } elseif (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe") {
          echo "Visual Studio 2022 Professional is installed"
        } elseif (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe") {
          echo "Visual Studio 2022 Community is installed"
        } else {
          echo "Visual Studio 2022 not found, checking other versions..."
          Get-ChildItem "C:\Program Files\Microsoft Visual Studio\" -ErrorAction SilentlyContinue | ForEach-Object { echo "Found: $($_.Name)" }
        }
        echo ""
        echo "CPU Core Information:"
        echo "Number of Logical Processors: $((Get-WmiObject -Class Win32_ComputerSystem).NumberOfLogicalProcessors)"
        echo "Number of Physical Processors: $((Get-WmiObject -Class Win32_ComputerSystem).NumberOfProcessors)"
        echo "Number of CPU Cores: $((Get-WmiObject -Class Win32_Processor).NumberOfCores)"
        echo ""
        echo "=== Detailed System Information ==="
        systeminfo
